/*
 * Copyright (c) 2010-2013 Evolveum and contributors
 *
 * Licensed under the EUPL-1.2 or later.
 */


//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.05.20 at 05:41:15 PM CEST
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://prism.evolveum.com/xml/ns/public/types-3", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.evolveum.prism.xml.ns._public.types_3;
